dpdk: fix do_install error for test programs
The commit 8c2fb513234a599edb481f74f74cafe09561a4ee introduces an error
when installing test programs:

/buildarea//build/tmp/work/intel_corei7_64-poky-linux/dpdk/19.11.0-r0/git/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal_memory.o):
In function `eal_legacy_hugepage_init':
eal_memory.c:(.text+0x1f71): undefined reference to `memfd_create'
/buildarea/build/tmp/work/intel_corei7_64-poky-linux/dpdk/19.11.0-r0/git/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal_memalloc.o):
In function `get_seg_fd.constprop.0':
eal_memalloc.c:(.text+0x61f): undefined reference to `memfd_create'
eal_memalloc.c:(.text+0x696): undefined reference to `memfd_create'
/buildarea/build/tmp/work/intel_corei7_64-poky-linux/dpdk/19.11.0-r0/git/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal_memalloc.o):
In function `eal_memalloc_init':
eal_memalloc.c:(.text+0x21ad): undefined reference to `memfd_create'
/buildarea/build/tmp/work/intel_corei7_64-poky-linux/dpdk/19.11.0-r0/git/x86_64-native-linuxapp-gcc/lib/librte_pmd_memif.a(rte_eth_memif.o):rte_eth_memif.c:(.text+0xbc3): more undefined references to `memfd_create' follow
collect2: error: ld returned 1 exit status

The test programs have been complied and install to ${S}/test/app
directory. We just need to ship them to ${D} directory.

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>