dpdk-module: use netif_rx() instead of netif_rx_ni()
The netif_rx_ni is removed in below commit after kernel upgraded
to 5.18, so use netif_rx() instead of netif_rx_ni() to fix the gap.
2655926aea9b net: Remove netif_rx_any_context() and netif_rx_ni().

Fixes:
  | TOPDIR/tmp-glibc/work/intel_x86_64-wrs-linux/dpdk-module/21.11.0-r0/git/kernel/linux/kni/kni_net.c: In function 'kni_net_rx_normal':
  | TOPDIR/tmp-glibc/work/intel_x86_64-wrs-linux/dpdk-module/21.11.0-r0/git/kernel/linux/kni/kni_net.c:444:17: error: implicit declaration of function 'netif_rx_ni'; did you mean 'netif_rx'? [-Werror=implicit-function-declaration]
  444 |                 netif_rx_ni(skb);

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>