dpdk: fix compile failure on gcc10
Since oe-core upgraded gcc to 10.1, there is a failure
...
|path_to_dpdk/19.11.1-r0/git/examples/ipsec-secgw/ipsec_process.c:131:34:
error: 'grp.m' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
|  131 |    grp[n].cnt = pkts + i - grp[n].m;
...

Add option `-Wno-error=maybe-uninitialized' to workaround

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>