dpdk.inc: fix missing numa.h by disabling NUMA options by default
Otherwise we get this:

| dpdk-18.02/lib/librte_eal/linuxapp/eal/eal_memory.c:27:10: fatal error: numa.h: No such file or directory
|  #include <numa.h>
|           ^~~~~~~~
| compilation terminated.

Use PACKAGECONFIG to optionally enable the numa option.

Signed-off-by: California Sullivan <california.l.sullivan@intel.com>