dpdk: backport patches to fix build
Currently, a number of integer types are typedef'd to their corresponding
userspace or RTE values. This can be problematic if these types are already
defined somewhere else, as it would cause type collisions.

The error like this:
gve_osdep.h:45:20: error: conflicting types for '__le64';
have 'rte_le64_t' {aka 'long unsigned int'} | 45 | typedef rte_le64_t __le64; | | ^~~~~~ |
....
recipe-sysroot/usr/include/linux/types.h:35:25: note: previous declaration of
'__le64' with type '__le64' {aka 'long long unsigned int'} | 35 | typedef __u64 __bitwise __le64;

The upstream has already fixed, backport them to 23.11.x.

Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>